# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('simulation-proposal', ['core','olsr','applications','internet','mobility'])
    module.source = [
        'model/simulation-proposal.cc',
        'model/simulation-proposal2.cc',
        'model/rand-simulation.cc',
        'model/seq-ts-size-header2.cc',
        'helper/simulation-proposal-helper.cc',
        'helper/simulation-proposal-helper2.cc',
        ]

   # module_test = bld.create_ns3_module_test_library('new-module')
   # module_test.source = [
   #    'test/new-module-test-suite.cc',
   #    ]
    # Tests encapsulating example programs should be listed here
   # if (bld.env['ENABLE_EXAMPLES']):
   #     module_test.source.extend([
        #    'test/new-module-examples-test-suite.cc',
   #          ])

    headers = bld(features='ns3header')
    headers.module = 'simulation-proposal'
    headers.source = [
        'model/simulation-proposal.h',
        'model/simulation-proposal2.h',
        'model/rand-simulation.h',
        'model/seq-ts-size-header2.h',
        'helper/simulation-proposal-helper.h',
        'helper/simulation-proposal-helper2.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

